### ISSUE TITLE
在MAYA_PLUG_IN_PATH上找不到插件“rfm_volume_aggregate_set.py”

### ISSUE THREAD

**Issue by martin-wmx** [benject/mirror#1]
您好，我在maya上运行了您的代码，在执行弹出窗口第二步（也就是打开mb场景文件）时，遇到了报错：
**在MAYA_PLUG_IN_PATH上找不到插件“rfm_volume_aggregate_set.py”**
**在MAYA_PLUG_IN_PATH上找不到插件“RenderMan_for_Maya.py**
我使用的maya版本是2023，请问有什么解决办法么？

**Comment by benject** [comment]
这个不影响啊。

**Comment by martin-wmx** [comment]
加载动画文件，我用的是sample\video_clip.json，然后开始动画，但是生成的效果只是脸部模型前后翻转，没有表情变化

> 这个不影响啊。

**Comment by martin-wmx** [comment]
我明白了，json文件只有第一帧的，处理视频文件的代码有问题，需要把每一帧的468个坐标都写入对吧

**Comment by benject** [comment]
你好 有一个参数 是 video

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by martin-wmx** [comment]
好的，非常感谢，现在有效果了

**Comment by benject** [comment]
哈哈 很高兴能帮到你

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
